# Generated by Django 4.1.6 on 2023-02-11 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buyers",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("value", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=11)),
                ("value", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ResDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "result",
                    models.IntegerField(
                        choices=[(0, "Sell"), (1, "Proccess")], default=0
                    ),
                ),
                (
                    "Workers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Manage.worker"
                    ),
                ),
            ],
        ),
    ]
