# Generated by Django 4.1.6 on 2023-02-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Manage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="resday", name="Workers",),
        migrations.AddField(
            model_name="resday",
            name="Workers",
            field=models.ManyToManyField(to="Manage.worker"),
        ),
    ]
