# Generated by Django 4.1.6 on 2023-02-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Manage", "0002_remove_resday_workers_resday_workers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resday",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
