# Generated by Django 4.1.6 on 2023-02-11 22:18

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("Manage", "0003_alter_resday_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resday",
            name="date",
            field=django_jalali.db.models.jDateTimeField(verbose_name="تاریخ تحویل"),
        ),
    ]
