# Generated by Django 4.1.6 on 2023-02-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Manage", "0004_alter_resday_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resday", name="date", field=models.DateField(),
        ),
    ]
